language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://n.tkte.ch/h/481/b3asBm0VcsMd9N2Byej5qaYp

env:
  global:
    - secure: "j0rO/v5/DWbEQ9ZTivdJw0rP4bzkwGVtMmpRvjVC0VfzQv3x10nQaMfyOTJIDOM/3vRW2lAGNZ5c5hnR0emzveXUPQ3DTOnFNzwSuurw24wSbxp+jQLVwdN2cZ3I6SZvyreCrAo6HUwEdpsIe+ySF45tpD/g+q9uI7AZE6M2ubw="
    - secure: "fhn2LyoBLbJuF2ejGAHXrxRnMvj5Wx7Jv7Fo0AK5HCTBaz0K8m7acetUlDhgtt+GmLM4B6d5Mg+z2zCG591Pwmfn0tlwfW3yi+hXq7SBmt581xOnnxESPsuGtRxN+nqKZipeJfT+scvakCEzb941zJG0xV8QZ3Z9k/K+x1mU2K4="
