language: java
jdk: oraclejdk7

install: mvn package -DbuildNumber=$TRAVIS_BUILD_NUMBER -DciSystem=travis -Dcommit=${TRAVIS_COMMIT:0:7}
after_success:
  - "git clone -b travis `git config --get remote.origin.url` target/travis"
  - "[[ \"$TRAVIS_BRANCH\" == \"master\" ]] && mvn deploy --settings target/travis/settings.xml"

notifications:
  email: false
  webhooks:
    - http://n.tkte.ch/h/481/b3asBm0VcsMd9N2Byej5qaYp

env:
  global:
    - secure: "fRmBfBSqddKdyLIxfO5ZU9fZADBKSzrHQwwCOiFNtka9pKhXqnYhDBPE5aascP54dGjHJ6vz6SYogTHzJR5jTG4zNfprYEoY/IuDEb8sKwaAHCEEouLQovI1maa9OA5Dz6fPafPpYDfCFNIJmF6EaiTMzKvD+v7DvMY8Zj30orE="
    - secure: "LWyZBgkccqMdseOkkKBMmnxQeZR63jBOYxk2Mv9p3PxukMIjlVFH1zLunQYypKcafaq9IOP1GxKRSuWa+WWvZMNcfKkYbc5CwWrdBL+aQhSnBVL6S30XU2tpJsFKsWMNJNffV8Ftg/fwGULp7hk0NQVbLzcLa88Hh8gIfQMPgXM="
